//jquery starts
$(document).ready(function(){
    function insert(num){
        $('.screen').text($('.screen').text()+num);
    }
    $('.b1').click(function(){
        insert(1);
    })
    $('.b2').click(function(){
        insert(2);
    })
    $('.b3').click(function(){
        insert(3);
    })
    $('.b4').click(function(){
        insert(4);
    })
    $('.b5').click(function(){
        insert(5);
    })
    $('.b6').click(function(){  
        insert(6);
    })
    $('.b7').click(function(){  
        insert(7);
    })
    $('.b8').click(function(){  
        insert(8);
    })
    $('.b9').click(function(){  
        insert(9);
    })
    $('.b0').click(function(){  
        insert(0);
    })  
    $('.bplus').click(function(){  
        insert('+');
    })
    $('.bminus').click(function(){  
        insert('-');
    })  
    $('.bmul').click(function(){
        insert('*');
    })
    $('.bdiv').click(function(){
        insert('/');
    })
    $('.bdot').click(function(){
        insert('.');
    })
    $('.bdel').click(function(){    
        $('.screen').text($('.screen').text().slice(0,-1));
    })
    $('.bre').click(function(){  
        $('.screen').text('');
    })
    $('.bequ').click(function(){
        $('.screen').text(eval($('.screen').text()));
    })
})